### PR TITLE
FEAT: Add support for parallel option and improve performance

### PR DESCRIPTION
**Pull request by amirha97**
Add parallelisation support (through multiprocessing) and some caching through memoization.

### CODE REVIEW

**Comment by nkmathew** [comment]
Do you find the memoization helps?

**Comment by amirha97** [comment]
Yes, in my case, it helped a noticeable amount. It depends on how repetitive the code is, which is more likely with larger codebases.

I also tried adding asyncio support as we discussed, but as you predicted it didn't help much at all. I didn't add full support, just to the outer file read, and the speedup was not significant at all, compared to this multiprocessing approach.

I used 2 approaches for profiling, cProfile and line_profile. Each led me to discover different functions as being potentially slow. cProfile showed great improvement when caching was added.
 
The most significant speed up from the caching us due to the profile config lookup, as that one gets called quite often and each time it tried to read a file from the home directory. 

I couldn't find any other easy wins to improve performance. I briefly looked at using a different regex engine as the regex computation is the bottleneck and found the re2 package but the interface is not the exact same so some refactoring will be needed.

**Comment by amirha97** [comment]
One more thing I forgot to mention, I reduced the number of newlines in the output when there are no files changes from 2 to 1. Let me know if you like this reverted, but I've found it's easier to view the output without the extra line breaks

**Comment by nkmathew** [comment]
> One more thing I forgot to mention, I reduced the number of newlines in the output when there are no files changes from 2 to 1. Let me know if you like this reverted, but I've found it's easier to view the output without the extra line breaks

Yeah it's fine. The spaced ellipsis too are really ugly. Don't even remember why I wanted it that way in the first place

**Comment by amirha97** [comment]
@nkmathew Should I make another PR to bump up the version and get ready for a new package release? I'm not sure what your process is and I've actually not done anything with python package releases before

**Comment by nkmathew** [comment]
No it's fine. There are a couple of little annoyances I want to fix first: typos, linting, failing tox builds

**Pull request merged**
